# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Screen.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1402, 675)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_Screen = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Screen.sizePolicy().hasHeightForWidth())
        self.label_Screen.setSizePolicy(sizePolicy)
        self.label_Screen.setFrameShape(QtWidgets.QFrame.Box)
        self.label_Screen.setText("")
        self.label_Screen.setScaledContents(True)
        self.label_Screen.setObjectName("label_Screen")
        self.horizontalLayout_2.addWidget(self.label_Screen)
        self.label = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setFrameShape(QtWidgets.QFrame.Box)
        self.label.setText("")
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.verticalLayout.addWidget(self.frame)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_Start = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_Start.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_Start.setFont(font)
        self.pushButton_Start.setStyleSheet("QPushButton#pushButton_Start{\n"
"    \n"
"    background-color: rgb(249, 166, 124);\n"
"}\n"
"\n"
"QPushButton#pushButton_Start:hover{\n"
"    background-color: rgb(255, 255, 0);\n"
"    \n"
"    color: rgb(0, 0, 127);\n"
"}\n"
"\n"
"QPushButton#pushButton_Start:pressed{\n"
"    \n"
"    background-color: rgb(0, 170, 0);\n"
"}")
        self.pushButton_Start.setObjectName("pushButton_Start")
        self.horizontalLayout.addWidget(self.pushButton_Start)
        self.pushButton_Stop = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_Stop.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.pushButton_Stop.setFont(font)
        self.pushButton_Stop.setStyleSheet("QPushButton#pushButton_Stop{\n"
"    \n"
"    background-color: rgb(170, 170, 255);\n"
"}\n"
"\n"
"QPushButton#pushButton_Stop:hover{\n"
"    background-color: rgb(255, 255, 0);\n"
"    color: rgb(0, 0, 127);\n"
"}\n"
"\n"
"QPushButton#pushButton_Stop:pressed{\n"
"    \n"
"    background-color: rgb(0, 170, 0);\n"
"}")
        self.pushButton_Stop.setObjectName("pushButton_Stop")
        self.horizontalLayout.addWidget(self.pushButton_Stop)
        self.verticalLayout.addWidget(self.frame_2)
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setMinimumSize(QtCore.QSize(50, 50))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_3)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lineEdit = QtWidgets.QLineEdit(self.frame_3)
        self.lineEdit.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.lineEdit.setFont(font)
        self.lineEdit.setText("")
        self.lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_3.addWidget(self.lineEdit)
        self.pushButton_Browser = QtWidgets.QPushButton(self.frame_3)
        self.pushButton_Browser.setMinimumSize(QtCore.QSize(200, 50))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pushButton_Browser.setFont(font)
        self.pushButton_Browser.setStyleSheet("QPushButton#pushButton_Browser{\n"
"    \n"
"    background-color: rgb(207, 138, 207);\n"
"}\n"
"\n"
"QPushButton#pushButton_Browser:hover{\n"
"    background-color: rgb(255, 255, 0);\n"
"    color: rgb(0, 0, 127);\n"
"}\n"
"\n"
"QPushButton#pushButton_Browser:pressed{\n"
"    \n"
"    background-color: rgb(0, 170, 0);\n"
"}")
        self.pushButton_Browser.setObjectName("pushButton_Browser")
        self.horizontalLayout_3.addWidget(self.pushButton_Browser)
        self.verticalLayout.addWidget(self.frame_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1402, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_Start.setText(_translate("MainWindow", "Start"))
        self.pushButton_Stop.setText(_translate("MainWindow", "Stop"))
        self.pushButton_Browser.setText(_translate("MainWindow", "Browser"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
